version: '3'
services:
  mongodb:
    image: 'mongo:5.0.7'
    command: mongod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "${APP_PORT}:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV
      - MONGO_URL
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app