version: '3'
services:
  mongodb:
    container_name: "${PREFIX_CONTAINER}-mongo"
    image: 'mongo:5.0.7'
    command: mongod
  nginx:
    container_name: "${PREFIX_CONTAINER}-nginx"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - ${APP_PORT}:80
  api:
    container_name: "${PREFIX_CONTAINER}-api"
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV
      - MONGO_URL
  client:
    container_name: "${PREFIX_CONTAINER}-client"
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app