version: '3'
services:
  mongodb:
    container_name: "${PREFIX_CONTAINER}-mongo"
    image: 'mongo:5.0.7'
    ports:
      - 27017:27017
    command: mongod
  nginx:
    container_name: "${PREFIX_CONTAINER}-nginx"
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - ${APP_PORT}:80
  api:
    container_name: "${PREFIX_CONTAINER}-api"
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server/:/app
    environment:
      - NODE_ENV
      - MONGO_URL
  client:
    container_name: "${PREFIX_CONTAINER}-client"
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app