FROM node:16.14.2 AS node

WORKDIR '/app'

COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

RUN apt update

RUN apt install libcurl4
RUN apt install ffmpeg -y

COPY . .

CMD ["npm", "run", "dev"]